# Generated by Django 3.0.2 on 2020-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamienniki', '0002_auto_20200106_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamiennik',
            name='liczba_ECTS',
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='formaKursu',
            field=models.CharField(default='a', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='formaZaliczenia',
            field=models.CharField(default='zaliczenie', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='kodKursu',
            field=models.CharField(default='abcd', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='liczbaECTS',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='liczbaGodzin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='slowaKluczowe',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='statusZamiennika',
            field=models.CharField(default='DoRozpatrzenia', max_length=10),
            preserve_default=False,
        ),
    ]
