# Generated by Django 3.0.2 on 2020-01-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicjatorzy', '0001_initial'),
        ('zamienniki', '0004_zamiennik_kartakursu'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamiennik',
            name='inicjator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicjatorzy.Inicjator'),
        ),
    ]
