# Generated by Django 3.0.2 on 2020-01-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamienniki', '0005_zamiennik_inicjator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamiennik',
            name='formaKursu',
        ),
        migrations.AddField(
            model_name='zamiennik',
            name='formaZajec',
            field=models.CharField(choices=[('WYK', 'Wykład'), ('LAB', 'Laboratorium'), ('SEM', 'Seminarium'), ('PROJ', 'Projekt'), ('CW', 'Ćwiczenie')], default='WYK', max_length=20),
        ),
        migrations.AlterField(
            model_name='zamiennik',
            name='formaZaliczenia',
            field=models.CharField(choices=[('EG', 'Egzamin'), ('ZNO', 'Zaliczenie na ocenę')], default='ZNO', max_length=20),
        ),
        migrations.AlterField(
            model_name='zamiennik',
            name='statusZamiennika',
            field=models.CharField(choices=[('OCZEK', 'Oczekujący'), ('ODRZ', 'Odrzucony'), ('AKCP', 'Zaakceptowany')], default='OCZEK', max_length=10),
        ),
    ]
