# Generated by Django 3.0.2 on 2020-01-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamienniki', '0007_auto_20200115_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamiennik',
            name='formaZajec',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='formaZaliczenia',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='kartaKursu',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='kodKursu',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='liczbaECTS',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='liczbaGodzin',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='zamiennik',
            name='slowaKluczowe',
        ),
    ]
