# Generated by Django 3.0.2 on 2020-01-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0003_auto_20200115_1539'),
        ('inicjatorzy', '0004_auto_20200121_1944'),
        ('zamienniki', '0008_auto_20200125_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamiennik',
            name='kursZamieniany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kursy.Kurs'),
        ),
        migrations.AlterField(
            model_name='zamiennik',
            name='inicjator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicjatorzy.Inicjator'),
        ),
    ]
