# Generated by Django 3.0.2 on 2020-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0003_auto_20200115_1539'),
        ('zamienniki', '0009_auto_20200125_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamiennik',
            name='kursyZamiennikia',
            field=models.ManyToManyField(related_name='_zamiennik_kursyZamiennikia_+', to='kursy.Kurs'),
        ),
    ]
