# Generated by Django 3.0.2 on 2020-01-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0003_auto_20200115_1539'),
        ('zamienniki', '0011_auto_20200125_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamiennik',
            name='kursyZamiennika',
            field=models.ManyToManyField(related_name='kursyWchodząceWSkładZamiennika', to='kursy.Kurs'),
        ),
    ]
