# Generated by Django 3.0.2 on 2020-01-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0003_auto_20200115_1539'),
        ('zamienniki', '0012_auto_20200125_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamiennik',
            name='kursZamieniany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zamiennik', to='kursy.Kurs'),
        ),
    ]
