# Generated by Django 3.0.2 on 2020-01-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planstudiow', '0001_initial'),
        ('zamienniki', '0013_auto_20200125_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamiennik',
            name='planstudiow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planstudiow.PlanStudiow'),
        ),
    ]
