# Generated by Django 3.0.2 on 2020-01-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamienniki', '0014_zamiennik_planstudiow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamiennik',
            name='planstudiow',
        ),
    ]
