# Generated by Django 3.0.2 on 2020-01-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicjator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('haslo', models.CharField(max_length=500)),
                ('indeks', models.PositiveSmallIntegerField()),
                ('rola', models.CharField(max_length=20)),
            ],
        ),
    ]
