# Generated by Django 3.0.2 on 2020-01-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicjatorzy', '0002_auto_20200114_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicjator',
            name='indeks',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
