# Generated by Django 3.0.2 on 2020-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicjatorzy', '0003_auto_20200114_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicjator',
            name='indeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
