# Generated by Django 3.0.2 on 2020-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicjatorzy', '0004_auto_20200121_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicjator',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
