# Generated by Django 3.0.2 on 2020-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanStudiow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stpienStudiow', models.CharField(choices=[('P', 'I'), ('D', 'II')], default='P', max_length=20)),
                ('formaStudiow', models.CharField(choices=[('S', 'Stacjonarne'), ('NS', 'Niestacjonarne')], default='S', max_length=20)),
                ('jezykStudiow', models.CharField(max_length=30)),
                ('specjalnosc', models.CharField(max_length=30)),
                ('liczbaSemestrow', models.PositiveIntegerField()),
                ('obowiazujeOd', models.DateField()),
            ],
        ),
    ]
