# Generated by Django 3.0.2 on 2020-01-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodKursu', models.CharField(max_length=8)),
                ('nazwa', models.TextField()),
                ('liczbaECTS', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('formaZaliczenia', models.CharField(max_length=80)),
                ('liczbaGodzin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('formaKursu', models.CharField(max_length=15)),
                ('kartaKursu', models.CharField(max_length=80)),
            ],
        ),
    ]
