# Generated by Django 3.0.2 on 2020-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='liczbaECTS',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kurs',
            name='liczbaGodzin',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
