# Generated by Django 3.0.2 on 2020-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0002_auto_20200115_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='formaKursu',
        ),
        migrations.AddField(
            model_name='kurs',
            name='formaZajec',
            field=models.CharField(choices=[('WYK', 'Wykład'), ('LAB', 'Laboratorium'), ('SEM', 'Seminarium'), ('PROJ', 'Projekt'), ('CW', 'Ćwiczenie')], default='WYK', max_length=20),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='formaZaliczenia',
            field=models.CharField(choices=[('EG', 'Egzamin'), ('ZNO', 'Zaliczenie na ocenę')], default='ZNO', max_length=20),
        ),
    ]
