# Generated by Django 3.0.2 on 2020-01-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planstudiow', '0001_initial'),
        ('kursy', '0003_auto_20200115_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='planstudiow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planstudiow.PlanStudiow'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='kodKursu',
            field=models.CharField(max_length=15),
        ),
    ]
