# Generated by Django 3.0.2 on 2020-01-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursy', '0004_auto_20200126_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='liczbaECTS',
            new_name='ECTS',
        ),
    ]
